### ISSUE TITLE
[Functional Bug]: angeschnittene Zeile in der Ergebnisübersicht

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cda-orga#60]
### URL of the buggy page?

https://lucascranach.org/de/search/

### Contact Details

cn

### What happened?

Bei der 2. Galerieansicht gibt es jetzt wieder eine angeschnittene Zeile, d.h. die Anpassung der Übersicht auf die jeweilige Bildschirmgröße ist möglicherweise mit der Neuerung nicht übernommen?

**Comment by CranacharchivGunnar** [comment]
![Unbenannt-1](https://user-images.githubusercontent.com/106104186/182387905-087fd99c-b6b0-4b3c-aae4-93a0bd48809e.jpg)

**Comment by CranacharchivGunnar** [comment]
S. Screenshot

**Comment by jhfpereira** [comment]
Möglicher MergeRequest mit einem Fix für dieses Problem: https://github.com/lucascranach/cranach-search/pull/90

**Comment by CranacharchivGunnar** [comment]
Hi Jorge,
das sieht wieder richtig gut aus! Simply Perfect! Danke Dir!
Herzlich,
G

**Comment by CranacharchivGunnar** [comment]
Sorry, am Anfang funktioniert das gut, wenn ich allerdings einen Filter Setze, z.B. unter Zuschreibung "Lucas Cranach d. Ä" und dann anschließend auf "Filter zurücksetzen" klicke, dann bleibt es nicht bei der reduzierten Zeilenanzahl, dann werden mehr Zeilen angezeigt als auf die Seite passen, auch wenn ich weitere Filter betätige. Kann das nur rücksetzen, wenn ich zwischenzeitlich die andere Ansicht aufrufe und dann nochmal zurückwechsle...

**Comment by jhfpereira** [comment]
@CranacharchivGunnar Hallo Gunnar,

habe mir auch das hier nochmal angeschaut.
Eine hoffentlich bessere Version habe intern deployed. ( https://lucascranach.org/de/intern/search/ )
Schau bitte bei Gelegenheit, ob das von dir beschriebene Problem noch reproduzierbar oder behoben ist.

**Comment by CranacharchivGunnar** [comment]
Hi Jorge,
wunderbar. Kann den Fehler nicht mehr reproduzieren...
Herzliche Dankesgrüße aus den Bergen!

Gunnar





>>> "Jorge H. F. Pereira" ***@***.***> 21.08.22 17.34 Uhr
>>>

 @CranacharchivGunnar Hallo Gunnar,
 habe mir auch das hier nochmal angeschaut.
 Eine hoffentlich bessere Version habe intern deployed. (
https://lucascranach.org/de/intern/search/ )
 Schau bitte bei Gelegenheit, ob das von dir beschriebene Problem noch
reproduzierbar oder behoben ist.
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by jhfpereira** [comment]
Super,

dann schließe ich das Issue hiermit.

**Comment by CranacharchivGunnar** [comment]
Hi Jorge,
das sieht wieder richtig gut aus! Simply Perfect! Danke Dir!
Herzlich,
G





>>> "Jorge H. F. Pereira" ***@***.***> 08.08.22 17.35 Uhr
>>>

 @CranacharchivGunnar Ein Fix würde für die internen und die öffentliche
Suche ausgespielt. Bitte einmal testen, ob die letzte Zeile nun nicht
mehr angeschnitten ist.
 —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>
